version: '2'
services:
    db:
        image: mongo
        volumes:
            - ./data/db:/data/db

    be:
        image: marcopeg/node
        links:
            - db:db
        volumes:
            - ./src/api:/usr/src/app
            - ./src/html:/usr/src/html
        ports:
            - 1080:8080
        entrypoint: ["npm", "start"]
