version: '2'
services:

    db:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ./data/db:/data/db

    be:
        image: marcopeg/node
        links:
            - db:db
        volumes:
            - ./src/api:/usr/src/app
            - ./src/html:/usr/src/html
        ports:
            - 8080:8080
        entrypoint: ["npm", "run", "start:dev"]
